name = "Create Train World"
author = "CobaltDragon_"
version = "1.2.1"
pack-format = "packwiz:1.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d3ab130dbc7dacafd92210b70bd4b17fc1a2808524a51e8a073b4ada3ad8de6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = ["list"]
datapack-folder = "config/openloader/datapacks"
