name = "Create Train World"
author = "CobaltDragon_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "285fc685b7400d854a2f2a83181fa0856f9a2c0dab83a1ee574ac7b2a4ca7343"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
acceptable-game-versions = ["list"]
datapack-folder = "config/openloader/datapacks"
