name = "Create Train World"
author = "CobaltDragon_"
version = "1.2.1"
pack-format = "packwiz:1.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1603162f1c6a0c5481bb2c26fcc7354a0463356b40122b0d6948906d2f1fbfdb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = ["list"]
datapack-folder = "config/openloader/datapacks"
